config/routes.rb
Rails.application.routes.draw do
  root "cocktails#index"
  resources :cocktails do
    resources :doses, only: [ :index, :new, :show, :create ]
  end
  resources :doses, only: [ :new, :create, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates_associated :ingredient
  validates_associated :cocktail
  validates :description, presence: true
  validates :ingredient, presence: true, allow_blank: false
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail_instance, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
    @doses = Dose.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktails_path
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail_instance
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose_instance, only: [:index, :show, :edit, :update]
  def index
    @cocktail = Cocktail.find(params[:cocktail_id])
    @doses = Dose.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @ingredient = Ingredient.find(params[:dose][:ingredient_id])
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    @dose.ingredient = @ingredient
    if @dose.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private
  def set_dose_instance
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_navbar.html.erb
<div class="navbar-wagon">
<!-- Logo -->
  <a href="/" class="navbar-wagon-brand"><i class="fa fa-glass-martini"></i> Cocktails</a>
<!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <i class="fa fa-plus"></i><%= link_to "Add a new cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %>
  </div>
</div>

app/views/cocktails/edit.html.erb
<!-- <h1>Editing <%= @cocktail.name %></h1>
<hr> -->

<%= simple_form_for @cocktail do |f| %>

  <% if @cocktail.errors.any? %>
    <div class="errors-container">
      <ul style="color:red;list-style: none;font-weight:bold;">
        <% @cocktail.errors.full_messages.each do |message| %>
          <li>Error: <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <%= f.label :name, 'C O C K T A I L - N A M E', style: "color: white; font-weight: bold;" %>
      <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :photo, 'C O C K T A I L - P I C T U R E', style: "color: white; font-weight: bold;" %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
  <div style="padding-top:10px;color:white;">
    <i style="color:white;" class="fa fa-history"></i> <%= link_to "Back to index",  cocktails_path, style: "color: white; text-align:center;" %> | <i style="color:white;" class="fa fa-plus-square"></i> <%= link_to "Add a new dose",  new_cocktail_dose_path(@cocktail), style: "color: white; text-align:center;" %>
  </div>
<% end %>

app/views/cocktails/index.html.erb
<!-- <h1>Cocktails Manager</h1>
<hr> -->
<div class="flex">
  <% @cocktails.each do |cocktail| %>
    <div class="card" style="width: 18rem; margin:10px;">
      <img class="card-img-top" src="<%= cocktail.photo %>" alt="Card image cap">
      <div class="card-body">

        <h5 class="card-title"><%= cocktail.name %> -
          <%= link_to "", cocktail_path(cocktail), method: :delete, data: { confirm: "Are you sure you want to delete this cocktail ?" }, :class => "far fa-trash-alt"%>
          <%= link_to "",  edit_cocktail_path(cocktail), :class => "fa fa-pencil-alt" %></h5>

           <% @doses.select do |dose| %>
             <% if cocktail.id == dose.cocktail_id %>
                <p style="font-size:15px; opacity:1; text-shadow: none;" class="card-text"><%= dose.ingredient.name %> (<%= dose.description %>) - <%= link_to "", dose_path(dose), method: :delete, data: { confirm: "Are you sure you want to delete this ingredient ?" }, :class => "far fa-trash-alt"%></p>
             <% end %>
           <% end %>

        <footer class="blockquote-footer"><i class="fa fa-plus-square"></i> <%= link_to "Add a new dose",  new_cocktail_dose_path(cocktail) %></footer>

      </div>
    </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<!-- <h1>Creating a cocktail</h1>
<hr> -->

<%= simple_form_for @cocktail do |f| %>

  <% if @cocktail.errors.any? %>
    <div class="errors-container">
      <ul style="color:red;list-style: none;font-weight:bold;">
        <% @cocktail.errors.full_messages.each do |message| %>
          <li>Error: <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'C O C K T A I L - N A M E', style: "color: white; font-weight: bold;" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :photo, 'C O C K T A I L - P I C T U R E', style: "color: white; font-weight: bold;" %>
    <%= f.input :photo, label: false %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
  <div style="padding-top:10px;">
    <i style="color: white;" class="fa fa-history"></i> <%= link_to "Back to index",  cocktails_path, style: "color: white; text-align:center;" %>
  </div>
<% end %>

app/views/cocktails/show.html.erb
<div class="card text-center">
  <div class="card-header" style="color:black;">
    <%= @cocktail.name %>
    <%= link_to "", cocktail_path(@cocktail), method: :delete, data: { confirm: "Are you sure you want to delete this cocktail ?" }, :class => "far fa-trash-alt"%>
    <%= link_to "",  edit_cocktail_path(@cocktail), :class => "fa fa-pencil-alt" %>
    </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to "Ajouter une dose",  new_cocktail_dose_path(@cocktail) %></h5>
  </div>
  <div class="card-footer text-muted">
    <p><i class="fa fa-history" style="color:black;"></i> <%= link_to "Back to index",  cocktails_path %></p>
  </div>
</div>

app/views/doses/_navbar.html.erb
<div class="navbar-wagon">
<!-- Logo -->
  <a href="/" class="navbar-wagon-brand"><i class="fa fa-glass-martini"></i> Cocktails</a>
<!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

  </div>
</div>

app/views/doses/index.html.erb
<h1>Doses for <%= @cocktail.name %></h1>
<hr>

<% @doses.each do |dose| %>
  <div class="card">
    <div class="card-header">
      <%= dose.id %>#
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p><%= dose.description %></p>
        <footer class="blockquote-footer"> <%= link_to "", dose_path(dose), method: :delete, data: { confirm: "Are you sure you want to delete this ingredient ?" }, :class => "far fa-trash-alt"%></footer>
      </blockquote>
    </div>
  </div>
<% end %>

app/views/doses/new.html.erb
<!-- <h1>Adding a dose for <%= @cocktail.name %></h1>
<hr> -->

<%= simple_form_for [@cocktail, @dose] do |f| %>

  <% if @cocktail.errors.any? %>
    <div class="errors-container">
      <ul style="color:red;list-style: none;font-weight:bold;">
        <% @cocktail.errors.full_messages.each do |message| %>
          <li>Error: <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if @dose.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @dose.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, 'D O S E - D E S C R I P T I O N', style: "color: white; font-weight: bold;" %>
    <%= f.text_field :description, label: false, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :ingredient, 'S E L E C T - I N G R E D I E N T', style: "color: white; font-weight: bold;" %>
    <%= f.association :ingredient, label: false, class: "form-control" %>
  </div>
  <%= f.submit "Add a new dose", class: "btn btn-primary" %>
  <div style="padding-top:10px;">
    <i style="color: white;" class="fa fa-history"></i> <%= link_to "Back to index",  cocktails_path, style: "color: white; text-align:center;" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Mister Cocktails</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  </head>

  <body>
    <%= render "navbar" %>
    <div class="banner">
      <div class="banner-content">
        <h1 style="text-align:center;">C O C K T A I L S</h1>
        <p style="color:white; text-align:center;">Create your own cocktails!</p>
        <hr>
        <div class="container">
          <%= yield %>
        </div>


      </div>
    </div>




  </body>
</html>